#!/usr/bin/perl -w
use CGI;
use Redis;
$redis = new Redis;
$query = new CGI;
$log=0;
print $cgi->header(-charset => 'utf-8');
print $query->start_html('Log In');
if ($query->param('name')) {
	$yourName = $query->param('name'); #nombre introducido en formulario.
	@listNames = $redis->hkeys('namepass'); #obtiene las keys del hash namepass, previamente creado*.
	$success = 0; #Esta variable podría ser booleana. (queda por investigar su uso en perl.)
	
	foreach $name(@listNames){
		if($name eq $yourName){
			$success = 1; 
		}
	}

	if($success == 1){
	      print $query->h3('Bienvenido: ' . $yourName); #Pendiente añadir aquí la comprobación de la contraseña.
	} else {
	      print $query->h3('Lo sentimos! ');
	      print $query->h4('El usuario ' . $yourName . ' no está registrado');
	}
}
if (!$query->param) {
            print $query->start_form;
	    print $query->p('Nombre');
	    print $query->textfield(-name=>'name',
                -size=>35,
                -maxlength=>50,
		required);
	    print $query->p('Password');
            print $query->password_field(-name=>'password',
                -size=>35,
                -maxlength=>50,
		required);
            print $query->br;
            print $query->submit(-value=>'Log In');
            print $query->end_form;
}
print $query->end_html;

#* Queda pendiente controlar la creación del hash en Redis en caso de que no exista.
