#!/usr/bin/perl -w
use CGI;
use Redis;
$query = new CGI;

sub conectarRedis();

print $query->header(-charset => 'utf-8');
print $query->start_html('Log In');

$mens = "";

eval { conectarRedis() };
if($@) {
    $mens = "Lo sentimos la Aplicación está en mantenimiento";
}
if(!$mens and !$redis->exists('namepass')) {
    $mens = "Problema en estructuras de datos de la aplicación, hable con Admin";
}
if($mens) {
    print $query->h3($mens);
    print $query->end_html;
    exit;
}

if($query->param('mode')) {
  $mode=$query->param('mode');
  $yourName = $query->param('name'); #nombre introducido en formulario.
  $yourPasswd = $query->param('password');
  $success = 0;
  if ($mode eq 'Log In') {
        if($redis->hget('namepass',$yourName) eq $yourPasswd) {
	   $success = 1; 
        }
        if($success == 1){
	      print $query->h3('Bienvenido: ' . $yourName); 
        }
        else {
	      print $query->h3('Lo sentimos!');
#	      print $query->h4('El usuario ' . $yourName . ' no está registrado');
	      print $query->h4('usuario/password incorrectos');
        }
  }
  if ($mode eq 'Log Up') {
        if(!$redis->hexists('namepass',$yourName)) {
           $redis->hset('namepass',$yourName,$yourPasswd);
	   $success = 1;
        }
	if($success == 1){
	      print $query->h3('Bienvenido: ' . $yourName); 
	} else {
	      print $query->h3('Lo sentimos!');
	      print $query->h4('Elija otro nombre de usuario');
	} #Aún quedan cosas que desarrollar en este bloque.
	#La idea es separar el formulario de registro del de identificación.
  }
}

if (!$query->param) {
        print $query->start_form;

	    print $query->p('Nombre');
	    print $query->textfield(-name=>'name',
                -size=>35,
                -maxlength=>50,
		-required => "required", #Esta línea impide que se pueda enviar el formulario con esta línea en blanco.
		);

	    print $query->p('Password');
            print $query->password_field(-name=>'password',
                -size=>35,
                -maxlength=>50,
		-required=>"required",
		);

            print $query->br;
	
	#Quería implementar esto con radiobutton, pero no he encontrado el código correcto para hacerlo.
	    print $query->p('New here?');
	    print $query->scrolling_list(-name=>'mode',
				 -values=>['Log In','Log Up'],
				 -size=>2,
				 -multiple=>'false',
				 -default=>'Log In');

            print $query->br;
            print $query->submit(-value=>'Go');

            print $query->end_form;
}

print $query->end_html;

#* Queda pendiente controlar la creación del hash en Redis en caso de que no exista.
# IDEA: comprobar que redis está funcionando lanzando ping.
sub conectarRedis() {
  $redis = new Redis;
}
